# Starter pipeline
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Evaluación gratuita(802d13f5-2c6f-4a1c-84bd-2d154e1275d2)'
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    scriptPath: 'https://github.com/mitzysomadosi/pruebapipeline2/blob/master/pipeline2'


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

    stage('Terraform init') {
        sh 'terraform init'    
    }
    stage('Terraform plan') {
        
        sh "terraform plan"  
    } 
    stage('Terraform apply') {
          
        sh "terraform apply -auto-approve"
    }
     stage('Terraform show') {
       
        sh "terraform show -json"
     }

- script: |
  
