# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

    stage('Terraform init') {
        sh 'terraform init'    
    }
    stage('Terraform plan') {
        
        sh "terraform plan"  
    } 
    stage('Terraform apply') {
          
        sh "terraform apply -auto-approve"
    }
     stage('Terraform show') {
       
        sh "terraform show -json"
     }

- script: |
  
